name: Deploy Docker app to Hugging Face Space

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full repo (not shallow)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies (git-lfs + HF CLI)
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install
          pip install huggingface_hub

      - name: Clone Hugging Face Space repo
        run: |
          git clone https://huggingface.co/spaces/kacbar/asi-proj space-repo

      - name: Copy current project to Space repo
        run: |
          rsync -av --exclude=.git --exclude=space-repo ./ space-repo/

      - name: Commit and push to HF Space
        env:
          HF_TOKEN: ${{ secrets.ASITOKEN }}
        run: |
          cd space-repo
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git remote set-url origin https://kacbar:${HF_TOKEN}@huggingface.co/spaces/kacbar/asi-proj

          git lfs track "*.csv" "*.zip" "*.pkl" "*.png"
          git add .gitattributes
          git add .
          git commit -m "Deploy student depression Streamlit app to Hugging Face Space" || echo "No changes to commit"
          git push origin main
