name: Deploy Docker app to Hugging Face Space

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full repo (not shallow)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs rsync
          git lfs install
          git lfs pull

      - name: Clone Hugging Face Space repo
        env:
          HF_TOKEN: ${{ secrets.ASITOKEN }}
        run: |
          git clone https://huggingface.co/spaces/kacbar/asi-proj space-repo
          rsync -av --exclude=.git --exclude=space-repo ./ space-repo/

      - name: Deploy to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.ASITOKEN }}
        run: |
          cd space-repo
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git lfs install
          git lfs track "*.csv"
          git lfs track "*.zip"
          git lfs track "*.pkl"
          git lfs track "*.png"
          git add .gitattributes
          git add .
          git commit -m "Automatyczny deploy z GitHub Actions" || echo "Nic się nie zmieniło"
          git push https://kacbar:${HF_TOKEN}@huggingface.co/spaces/kacbar/asi-proj main
